# Navigation Links
[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40

[[main]]
   name = "CV"
   url = "files/cv.pdf"
   weight = 50
