baseURL = "https://utkarshverma.github.io"
title = "UtkarshVerma's Site"
theme = "dream-plus"
paginate = 4
ignoreFiles = ["content/404.md", "content/about.md", "content/posts/\\.*"]

googleAnalytics = "UA-112332904-3"
enableRobotsTXT = true
enableEmoji = true

[params]
	favicon = "/images/favicon.ico"
	contentType = "cards"
	siteStartYear = 2018
	
	[params.author]
		author = "Utkarsh Verma"
		description = "A hub for my works."
		avatar = "/images/avatar.jpg"
		motto = "A keen maker, programmer and an Instructables author."

	[params.background]
		colorBG = true

	[params.features]
		twitterEmoji = true
		coverArgs = "400x200 q100"

[social]
  email = "utkarshverma@pm.me"
  github = "UtkarshVerma"
  stackoverflow = "9271608/utkarsh-verma"
  medium = "UtkarshVerma_"
  twitter = "UtkarshVerma_"
